-- Early Access form table + security setup
-- Run in Supabase SQL Editor.

create table if not exists public.early_access_submissions (
    id bigint generated by default as identity primary key,
    first_name text,
    last_name text,
    contact text,
    message text,
    created_at timestamptz not null default now()
);

-- Enforce: at least one field must be provided.
do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'early_access_submissions_any_input_chk'
    ) then
        alter table public.early_access_submissions
            add constraint early_access_submissions_any_input_chk
            check (
                coalesce(nullif(btrim(first_name), ''), nullif(btrim(last_name), ''), nullif(btrim(contact), ''), nullif(btrim(message), '')) is not null
            );
    end if;
end $$;

alter table public.early_access_submissions enable row level security;

-- Allow public insert from browser using anon key.
do $$
begin
    if not exists (
        select 1
        from pg_policies
        where schemaname = 'public'
          and tablename = 'early_access_submissions'
          and policyname = 'anon_insert_early_access_submissions'
    ) then
        create policy anon_insert_early_access_submissions
            on public.early_access_submissions
            for insert
            to anon, authenticated
            with check (
                coalesce(nullif(btrim(first_name), ''), nullif(btrim(last_name), ''), nullif(btrim(contact), ''), nullif(btrim(message), '')) is not null
            );
    end if;
end $$;

grant usage on schema public to anon, authenticated;
grant insert on table public.early_access_submissions to anon, authenticated;
